package pojos;
// Generated 24-ene-2019 12:39:12 by Hibernate Tools 4.3.1

/**
 * Alumnos generated by hbm2java
 */
public class Alumnos implements java.io.Serializable {

    private Integer codigo;
    private String nombre;
    private String apellidos;

    public Alumnos() {
    }

    public Alumnos(String nombre, String apellidos) {
        this.nombre = nombre;
        this.apellidos = apellidos;
    }

    public Alumnos(int id, String nombre, String apellidos) {
        this.codigo = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
    }

    public Integer getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

}
